name: Wishlink Bot

on:
  schedule:
    - cron: "0 */2 * * *"  # every 2 hours
  workflow_dispatch:      # allows manual runs from the Actions tab

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run bot
        run: npm start
